name: Build docker Image

on:
  # All thoses triggers might be too much, subject to change
  push:
  pull_request:
  release:
    types: [published, created, edited]
  label:
    types: [created, edited]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -
        name: PrepareReg Names
        run: |
          # Change all uppercase to lowercase
          OWNER=$(echo ${{ github.repository_owner }} | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && LATEST="latest"
          
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          echo "OWNER=$OWNER"
          echo "VERSION=$VERSION"
      
      -
        name: Build container image
        uses: docker/build-push-action@v2
        with:
          context : .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/scirius:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/scirius:${{ env.VERSION }}
